name: Deploy to Heroku

on:
  push:
    branches:
      - master

env:
  SENTRY_DSN: https://533e56d1b2d64314bd6092a574e6d0f1@o74047.ingest.sentry.io/215496

jobs:
  release_manager:
    name: Release Manager
    runs-on: ${{ matrix.os }}
    environment: Production Outline Manager
    strategy:
      matrix:
        os: [ubuntu-20.04]
      # Don't cancel jobs on other platforms if one fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Show Environment Info
        run: |
          npm -v
          openssl version
          env

      - name: Install Dependencies
        run: npm install --production

      - name: Release Linux
        if: runner.os == 'Linux'
        run: npm run action server_manager/electron_app/release_linux

      - name: Show Environment Info
        run: |
          ls

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          files: "build/server_manager/electron_app/static/dist/*.*"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "outline-server-test" #Must be unique in Heroku
          heroku_email: "amygovenco@gmail.com"
          procfile: "web: npm start"
